grafana:
  adminPassword: prom-operator
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 7d
    resources:
      requests: { cpu: 100m, memory: 400Mi }
      limits:   { cpu: 500m, memory: 1Gi }
alertmanager:
  alertmanagerSpec:
    resources:
      requests: { cpu: 10m, memory: 64Mi }
      limits:   { cpu: 100m, memory: 128Mi }
